version: '3'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django:
    container_name: pdk-django
#    image: pdk-django:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
#    volumes:
#      - .:/app
    ports:
      - "8000:8000"
    environment:
    - POSTGRES_PASSWORD:mysecretpassword
    - POSTGRES_USER=postgres
    - POSTGRES_DATABASE=postgres

  postgres:
    image: mdillon/postgis:9.6
    container_name: pdk-postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    environment:
      - POSTGRES_PASSWORD:mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    ports:
    - "5432:5432"
